const { analyzeImage } = require('../utils/aiAnalyzer');
const { generateNSPIREReport } = require('../utils/reportGenerator');
const Inspection = require('../models/Inspection');
const path = require('path');
const fs = require('fs');

/**
 * Perform AI Inspection on an uploaded image
 */
exports.inspectImage = async (req, res) => {
    try {
        const { inspectionId, propertyId, inspectorId, imageUrl, deficiencyData } = req.body;
        const imagePath = imageUrl || (req.file ? req.file.path : null);

        if (!imagePath) {
            return res.status(400).json({ success: false, message: 'No image provided (URL or file)' });
        }

        if (!inspectorId) {
            return res.status(400).json({ success: false, message: 'Inspector ID is required. Please log in again.' });
        }

        // Validate image path/URL
        if (typeof imagePath !== 'string' || imagePath.trim() === '') {
            return res.status(400).json({ success: false, message: 'Invalid image path or URL' });
        }

        // 1. Analyze with AI (passing user context)
        console.log(`Starting AI Analysis for: ${imagePath}`);
        const analysis = await analyzeImage(imagePath, deficiencyData);

        if (analysis.status === 'Pass') {
            return res.json({ success: true, message: 'No defects detected.', analysis });
        }

        // 2. Map AI result to NSPIRE Model (Merging AI + User Data)
        const userSelectedDeficiency = deficiencyData?.selectedDeficiency || {};

        const newDeficiency = {
            category: deficiencyData?.category || 'unit',
            subCategory: analysis.subCategory || deficiencyData?.category || 'General',
            // Prefer user selection if available, otherwise AI
            description: userSelectedDeficiency.selected || analysis.defect || 'AI Detected Deficiency',
            deficiencyDetails: userSelectedDeficiency.detail || analysis.defect,
            nspireCode: userSelectedDeficiency.code || null,
            severity: deficiencyData?.healthAndSafety ? mapSeverity(deficiencyData.healthAndSafety) : mapSeverity(analysis.severity),
            status: 'open',
            location: deficiencyData?.location || 'Building Site S',
            photos: [{
                url: imagePath,
                caption: `AI Analysis: ${analysis.defect}`
            }],
            notes: deficiencyData?.note ?
                `User Note: ${deficiencyData.note} | AI Analysis: ${analysis.defect}` :
                `Automatically generated by local AI analysis of component: ${analysis.item}`
        };

        // 3. Find or Create Inspection
        let inspection;
        
        // First, try to find by inspectionId if provided
        if (inspectionId) {
            inspection = await Inspection.findById(inspectionId);
        }
        
        // If not found and we have propertyId, try to find existing inspection for this property
        if (!inspection && propertyId) {
            inspection = await Inspection.findOne({ 
                property: propertyId,
                inspector: inspectorId 
            }).sort({ createdAt: -1 }); // Get the most recent one
        }

        if (!inspection) {
            // Create a new inspection
            inspection = new Inspection({
                inspectionId: `AI-${Date.now()}`,
                property: propertyId,
                inspector: inspectorId,
                scheduledDate: new Date(),
                inspectionDate: new Date(), // Set inspection date
                inspectionLevel: 'unit',
                status: 'completed', // Mark as completed when AI analysis is done
                createdBy: inspectorId
            });
        } else {
            // Update existing inspection to completed
            inspection.status = 'completed';
            inspection.inspectionDate = new Date();
        }

        inspection.deficiencies.push(newDeficiency);
        await inspection.save();

        // 4. PDF Generation removed from here to prevent timeouts.
        // Reports are now generated on-demand in the summary page or via specific endpoints.

        res.json({
            success: true,
            data: {
                inspectionId: inspection._id,
                deficiency: newDeficiency,
                reportUrl: null // PDF can be generated via /api/inspections/generate-pdf
            }
        });

    } catch (error) {
        console.error('AI Inspection Controller Error:', error);
        res.status(500).json({ success: false, message: error.message });
    }
};

/**
 * Download a generated report
 */
exports.getReport = async (req, res) => {
    const fileName = req.params.fileName;
    const filePath = path.join(__dirname, '../reports', fileName);

    if (fs.existsSync(filePath)) {
        res.download(filePath);
    } else {
        res.status(404).json({ message: 'Report not found' });
    }
};

/**
 * Utility to map AI severity strings to enum values
 */
function mapSeverity(severity) {
    const s = severity?.toLowerCase() || '';
    if (s.includes('life') || s.includes('threatening')) return 'life-threatening';
    if (s.includes('severe') || s === 'high') return 'severe';
    if (s.includes('moderate') || s === 'medium') return 'moderate';
    if (s.includes('low') || s.includes('minor') || s.includes('observation')) return 'low';
    return 'moderate';
}
